import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Popup from "../_components/Popup";
import MobilePopup from "../_components/MobilePopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-900 antialiased    `}
      >
       
        {children}
       <div className="fixed z-90 right-15 bottom-14 hidden md:block">
          <Popup />
        </div>

        {/* Mobile Popup */}
        <div className="fixed z-90 right-6 bottom-14 block md:hidden">
          <MobilePopup />
        </div>
      </body>
    </html>
  );
}

